config/routes.rb
Rails.application.routes.draw do


  get 'inicio/index'



  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',

  }

  resources :products do
    get 'comprar'
    collection do
      get 'vendidos'
    end
  end

root 'inicio#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :photo, ImageUploader
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/inicio_controller.rb
class InicioController < ApplicationController
  def index
    @products = Product.where(vendido:false)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /products
  # GET /products.json
def vendidos
  @products = Product.where(vendido: true)
end

def comprar
    @product =  Product.find(params[:product_id])

    respond_to do |format|
         @product.vendido = true
      if @product.save()
        format.html { redirect_to root_path, notice: 'Product was successfully Vendido.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: root_path.errors, status: :unprocessable_entity }
      end
    end

end

  def index
    @products = Product.where(user_id: current_user.id)
  end

  # GET /products/1
  # GET /products/1.json
  def show

  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.user_id =  current_user.id if user_signed_in?
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
         @product.user_id =  current_user.id if user_signed_in?
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:nombre, :descripción, :precio, :moneda, :vendido, :user_id,:photo)
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inicio_helper.rb
module InicioHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/inicio/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Nombre</th>
      <th scope="col">Descripción</th>
      <th scope="col">Precio</th>
      <th scope="col">Moneda</th>
      <th scope="col">Vendido</th>
      <th scope="col">User</th>
      <th scope="col">Imagen</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.nombre %></td>
        <td><%= product.descripción %></td>
        <td><%= product.precio %></td>
        <td><%= product.moneda %></td>
        <td><%= product.vendido %></td>
        <td><%= product.user.id %></td>
        <td><%= image_tag product.photo %></td>
        <td><%= link_to 'Comprar',  product_comprar_path(product.id)  %></td>
      </tr>
    <% end %>.
  </tbody>
</table>

<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yapol</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>

  <body>

    <%= render "/shared/navbar" %>
      <% if notice.present? %>
      <div class="alert alert-success">
        <strong id='notice'><%= notice %></strong>
      </div>
      <% end %>
      <% if alert.present? %>
      <div class="alert alert-danger">
        <strong><%= alert %></strong> .
      </div>
      <% end %>




<div class="row text-center" >
  <div class="col-sm-3">
    <div id="list-example" >
      <ul>
        <li><%= link_to 'Pagina Principal', root_path,class:"  text-danger list-group-item list-group-item-action" %> </li>
        <% if user_signed_in? %>
            <li><%= link_to 'Ver Mis Productos', products_path,class:"  text-danger list-group-item list-group-item-action" %> </li>
            <li><%= link_to 'Ver Productos Vendidos', vendidos_products_path,class:"  text-danger list-group-item list-group-item-action" %> </li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="col-sm-8" >
      <%= yield %>
  </div>
</div>


<!--
<div class="container">
    <%= yield %>
</div> -->

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, id: :product_nombre %>
  </div>

  <div class="field">
    <%= form.label :descripción %>
    <%= form.text_field :descripción, id: :product_descripción %>
  </div>

  <div class="field">
    <%= form.label :precio %>
    <%= form.number_field :precio, id: :product_precio %>
  </div>

  <div class="field">
    <%= form.label :moneda %>
    <%= form.text_field :moneda, id: :product_moneda %>
  </div>

  <div class="field">
    <%= form.label :vendido %>
    <%= form.check_box :vendido, id: :product_vendido %>
  </div>

  <div class="field">
  <%= form.label :photo %>
  <%= form.file_field :photo, id: :photo_image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mis Products</h1>



  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Nombre</th>
        <th scope="col">Descripción</th>
        <th scope="col">Precio</th>
        <th scope="col">Moneda</th>
        <th scope="col">Vendido</th>
        <th scope="col">User</th>
        <th scope="col">Imagen</th>
        <th colspan="3"></th>
      </tr>
    </thead>


  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.nombre %></td>
        <td><%= product.descripción %></td>
        <td><%= product.precio %></td>
        <td><%= product.moneda %></td>
        <td><%= product.vendido %></td>
        <td><%= product.user.id %></td>
        <td><%= image_tag product.photo %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>.
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @product.nombre %>
</p>

<p>
  <strong>Descripción:</strong>
  <%= @product.descripción %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @product.precio %>
</p>

<p>
  <strong>Moneda:</strong>
  <%= @product.moneda %>
</p>

<p>
  <strong>Vendido:</strong>
  <%= @product.vendido %>
</p>

<p>
  <strong>User:</strong>
  <%= @product.user.email %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/products/vendidos.html.erb
<p id="notice"><%= notice %></p>

<h1>Mis Products Vendidos</h1>



  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Nombre</th>
        <th scope="col">Descripción</th>
        <th scope="col">Precio</th>
        <th scope="col">Moneda</th>
        <th scope="col">Vendido</th>
        <th scope="col">User</th>
        <th scope="col">Imagen</th>
      </tr>
    </thead>


  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.nombre %></td>
        <td><%= product.descripción %></td>
        <td><%= product.precio %></td>
        <td><%= product.moneda %></td>
        <td><%= product.vendido %></td>
        <td><%= product.user.id %></td>
        <td><%= image_tag product.photo %></td>
      </tr>
    <% end %>.
  </tbody>
</table>

<br>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="border-bottom: 5px solid  #F0AB00;">
    <a href="<%= root_path %>" class="navbar-brand">
    <%= image_tag "logo.png", class:'img-fluid', alt:'Logo' %>
    </a>
    <%= image_tag "logo_full.png", class:'img-fluid', alt:'Logo' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
      <li class="nav-link">
        <%= current_user.email %>
      </li>

        <li class="nav-item">
          <a class="nav-link" href="<%= destroy_user_session_path %>" data-method="delete"> Salir </a>
        </li>
      <% else %>
        <li class="nav-item active">
          <a class="nav-link" href="<%= new_user_session_path %>"> Ingresar <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= new_user_registration_path %>"> Registrarse </a>
        </li>



      <% end %>
    </ul>
  </div>
</nav>